// Generated by npm run outcomes:generate. Do not edit by hand.
import type { CompanyRecord, ProductRecord } from "./types.js";

export const rawCompanies: CompanyRecord[] = [
  {
    "schemaVersion": 1,
    "id": "bytedance",
    "name": "ByteDance",
    "website": "https://seed.bytedance.com/"
  },
  {
    "schemaVersion": 1,
    "id": "google-deepmind",
    "name": "Google DeepMind",
    "website": "https://deepmind.google/"
  },
  {
    "schemaVersion": 1,
    "id": "heygen",
    "name": "HeyGen",
    "website": "https://www.heygen.com"
  },
  {
    "schemaVersion": 1,
    "id": "remotion",
    "name": "Remotion",
    "website": "https://www.remotion.dev/"
  },
  {
    "schemaVersion": 1,
    "id": "three-js",
    "name": "Three.js",
    "website": "https://threejs.org/"
  },
  {
    "schemaVersion": 1,
    "id": "uzu",
    "name": "Uzu",
    "website": "https://strudel.cc/"
  }
];
export const rawProducts: ProductRecord[] = [
  {
    "schemaVersion": 1,
    "id": "bytedance/seedance",
    "name": "Seedance 2.0",
    "company": "bytedance",
    "category": "video",
    "summary": "Seedance 2.0 adopts a unified multimodal audio-video joint generation architecture that supports text, image, audio, and video inputs, leading to the most comprehensive multimodal content reference and editing capabilities in the industry.",
    "summarySourceUrl": "https://seed.bytedance.com/en/seedance2_0",
    "logoUrl": "https://lf3-static.bytednsdoc.com/obj/eden-cn/lapzild-tss/ljhwZthlaukjlkulzlp/favicon_1/favicon.ico",
    "website": "https://seed.bytedance.com/en/seedance2_0",
    "docsUrl": "https://seed.bytedance.com/en/seedance2_0"
  },
  {
    "schemaVersion": 1,
    "id": "google-deepmind/mujoco",
    "name": "MuJoCo",
    "company": "google-deepmind",
    "category": "robotics",
    "summary": "MuJoCo is a free and open source physics engine that aims to facilitate research and development in robotics, biomechanics, graphics and animation, and other areas where fast and accurate simulation is needed.",
    "summarySourceUrl": "https://mujoco.org/",
    "logoUrl": "https://mujoco.org/frontend/assets/favicon/favicon-32x32.png",
    "website": "https://mujoco.org/",
    "docsUrl": "https://mujoco.readthedocs.io/en/stable/overview.html"
  },
  {
    "schemaVersion": 1,
    "id": "heygen/hyperframes",
    "name": "HyperFrames",
    "company": "heygen",
    "category": "video",
    "summary": "HyperFrames is an open-source framework for turning HTML, CSS, media, and seekable animations into deterministic MP4 videos. Use it locally with the CLI, from AI coding agents with skills, or as the rendering core behind hosted authoring workflows.",
    "summarySourceUrl": "https://github.com/heygen-com/hyperframes/blob/3e4b08cdc18642d468d53f34c2fb64ab437807ae/README.md#L28",
    "logoUrl": "https://raw.githubusercontent.com/heygen-com/hyperframes/3e4b08cdc18642d468d53f34c2fb64ab437807ae/docs/logo/symbol-light.svg",
    "website": "https://github.com/heygen-com/hyperframes",
    "docsUrl": "https://hyperframes.heygen.com"
  },
  {
    "schemaVersion": 1,
    "id": "remotion/remotion",
    "name": "Remotion",
    "company": "remotion",
    "category": "video",
    "summary": "Create real MP4 videos with React. Use coding agents, build apps and render in bulk.",
    "summarySourceUrl": "https://www.remotion.dev/",
    "logoUrl": "https://www.remotion.dev/img/favicon.png",
    "website": "https://www.remotion.dev/",
    "docsUrl": "https://www.remotion.dev/docs/"
  },
  {
    "schemaVersion": 1,
    "id": "three-js/three-js",
    "name": "Three.js",
    "company": "three-js",
    "category": "3d",
    "summary": "Three.js is a 3D library that tries to make it as easy as possible to get 3D content on a webpage.",
    "summarySourceUrl": "https://threejs.org/manual/en/fundamentals.html",
    "logoUrl": "https://threejs.org/files/favicon_white.ico",
    "website": "https://threejs.org/",
    "docsUrl": "https://threejs.org/docs/"
  },
  {
    "schemaVersion": 1,
    "id": "uzu/strudel",
    "name": "Strudel",
    "company": "uzu",
    "category": "audio",
    "summary": "Strudel is a web-based live coding environment that implements the Tidal Cycles algorithmic pattern language.",
    "summarySourceUrl": "https://strudel.cc/learn/getting-started/",
    "logoUrl": "https://strudel.cc/icons/apple-icon-180.png",
    "website": "https://strudel.cc/",
    "docsUrl": "https://strudel.cc/learn/"
  }
];
