import type { OutcomePack } from "./types.js";
import { kickstarterFulfillmentPack } from "./kickstarter-fulfillment.js";

export const crowdfundingFulfillmentOperationsPack: OutcomePack = {
  schemaVersion: 1,
  catalogNumber: 28,
  lane: "operate",
  slug: "crowdfunding-fulfillment-operations",
  name: "Crowdfunding Fulfillment Operations",
  eyebrow: "28 / EXPERIMENTAL PACK",
  promise: "Operate one settled crowdfunding campaign to an honest obligation-level completion or blocked-state receipt.",
  summary: "A privacy-safe obligation ledger, bounded operating cycles, only the physical, digital, regional, address, exception, and communication modules that apply, and independently reconciled completion evidence.",
  useWhen: ["A crowdfunding funding run is funded and settled with real obligations.", "The team needs a durable control loop for production, delivery, exceptions, and backer commitments."],
  notFor: ["A campaign that is only prepared, live, unfunded, cancelled, or unsettled.", "A universal 95%-shipped target when obligations are digital, mixed, refunded, or otherwise non-shipping.", "Creating missing manufacturing or safety evidence inside fulfillment operations."],
  reviewedAt: "2026-07-29",
  schedule: { request: "Continue one bounded crowdfunding fulfillment cycle.", title: "Crowdfunding fulfillment cycle", description: "Reconcile obligations, execution evidence, exceptions, communications, and stop conditions.", safeDefault: "Do not purchase, manufacture, ship, message, refund, or expose backer data without exact authority." },
  skills: kickstarterFulfillmentPack.skills,
  workstreams: [
    { id: "ledger", name: "Obligation and authority baseline", skills: ["analytics", "security-review"], owns: ["fulfillment-operations/baseline/", "fulfillment-operations/ledger/"], brief: "Import only necessary settled obligations, pseudonymize records, define completion states, authorities, dependencies, budgets, and stop conditions." },
    { id: "operate", name: "Bounded fulfillment operation", skills: ["impediment-prioritization", "analytics"], owns: ["fulfillment-operations/cycles/", "fulfillment-operations/modules/"], dependsOn: ["ledger"], brief: "Execute the smallest approved cycle across active modules; preserve per-obligation evidence, exceptions, reversals, and waiting states." },
    { id: "reconcile", name: "Independent obligation reconciliation", skills: ["analytics", "security-review", "incident-postmortem"], owns: ["fulfillment-operations/review/", "fulfillment-operations/decision.json"], dependsOn: ["operate"], brief: "Reconcile every in-scope obligation without hiding failed delivery, refunds, replacements, disputes, exclusions, or unresolved blockers." },
  ],
  reviewSkills: ["analytics", "security-review", "incident-postmortem"],
  outputs: ["Privacy-safe obligation ledger", "Approved fulfillment authority and dependency baseline", "Dated operating cycle records", "Applicable module evidence and exception ledger", "Obligation-level decision receipt"],
  guardrails: ["Do not purchase, manufacture, access addresses, message backers, ship, refund, replace, or mutate provider state without exact approval and authority.", "Do not expose backer identity, contact, address, payment, tax, customs, or support data in general artifacts.", "Do not claim fulfillment from labels, tracking creation, bulk percentages, or shipped state alone; preserve delivered, failed, returned, refunded, replaced, disputed, and unknown states.", "Do not hide an unready production dependency inside operations; stop and identify the missing outcome or authority."],
  verification: ["Reconcile the settled funding receipt to the obligation ledger.", "Verify each terminal obligation state from direct evidence and preserve the denominator.", "Challenge privacy, regional, exception, refund, replacement, and communication controls for active modules.", "Write a complete, operating, blocked, repair-required, or no-go receipt without a universal shipment threshold."],
  prerequisites: [{ id: "funded-settled", description: "Crowdfunding Funding Run finished funded-settled for the exact campaign.", requiredEvidence: ["funding-run receipt", "settlement evidence", "immutable campaign and reward baseline"] }],
  expectations: [
    { id: "obligations-reconciled", statement: "The ledger accounts for every settled campaign obligation without duplication or silent exclusion.", failureModes: ["missing tier", "duplicate backer", "unexplained denominator"], requiredEvidence: ["settlement-to-ledger reconciliation"] },
    { id: "state-evidence", statement: "Every claimed terminal state has direct obligation-level evidence.", failureModes: ["label treated as delivery", "bulk percentage without records"], requiredEvidence: ["state evidence sample", "ledger audit"] },
    { id: "authority-bounded", statement: "External fulfillment actions stayed within approved authority.", failureModes: ["unapproved purchase", "unapproved message", "scope drift"], requiredEvidence: ["approval and action ledger"] },
    { id: "physical-proof", moduleId: "physical-rewards", statement: "Physical rewards follow verified production, quality, inventory, and delivery evidence.", failureModes: ["unverified batch", "inventory mismatch", "shipment without acceptance"], requiredEvidence: ["batch and quality records", "carrier and outcome evidence"] },
    { id: "digital-proof", moduleId: "digital-rewards", statement: "Digital rewards are delivered, accessible, and supportable for the named obligations.", failureModes: ["broken access", "license mismatch", "send treated as use"], requiredEvidence: ["delivery and access checks"] },
    { id: "regional-proof", moduleId: "regional-freight-customs", statement: "Active regions have explicit freight, customs, tax, restriction, and failure handling.", failureModes: ["prohibited shipment", "unpriced duties", "customs return"], requiredEvidence: ["regional route evidence"] },
    { id: "address-proof", moduleId: "backer-address-data", statement: "Address data is minimized, authorized, protected, and deleted or retained by policy.", failureModes: ["excess access", "stale address", "data leak"], requiredEvidence: ["data-flow audit", "access record"] },
    { id: "exception-proof", moduleId: "replacements-refunds", statement: "Replacements, refunds, returns, disputes, and failed delivery remain explicit and reconciled.", failureModes: ["exception erased", "double fulfillment", "unapproved refund"], requiredEvidence: ["exception ledger", "financial reconciliation"] },
    { id: "communications-proof", moduleId: "recurring-communications", statement: "Approved recurring communications are factual, consistent, and preserve responses and corrections.", failureModes: ["false date promise", "unapproved mass message", "contradictory update"], requiredEvidence: ["message archive", "approval record"] },
  ],
  modularOutcome: {
    kind: "modular-outcome", gateName: "Crowdfunding fulfillment operations", action: "Establish and run the first cycle of",
    contractPath: "fulfillment-operations/baseline/contract.json", moduleDecisionPath: "fulfillment-operations/baseline/modules.json", artifactRoot: "fulfillment-operations/", decisionReceiptPath: "fulfillment-operations/decision.json", minimumActiveModules: 1,
    modules: [
      { id: "physical-rewards", activationWhen: "At least one settled obligation requires a physical item.", work: ["control production, quality, inventory, packing, carrier handoff, and delivery states"], checks: ["reconcile units and test failed-delivery paths"], requiredExpectationIds: ["physical-proof"] },
      { id: "digital-rewards", activationWhen: "At least one settled obligation requires a digital deliverable or entitlement.", work: ["control versions, licenses, access, delivery, and support"], checks: ["test delivery and recipient access"], requiredExpectationIds: ["digital-proof"] },
      { id: "regional-freight-customs", activationWhen: "Physical obligations cross regions with material freight, customs, tax, or restriction exposure.", work: ["define region-specific routes and exception handling"], checks: ["verify restrictions, costs, documents, and returned paths"], requiredExpectationIds: ["regional-proof"] },
      { id: "backer-address-data", activationWhen: "Fulfillment requires access to backer addresses or related delivery data.", work: ["minimize, authorize, protect, correct, export, and dispose address data"], checks: ["audit access, transfers, retention, and deletion"], requiredExpectationIds: ["address-proof"] },
      { id: "replacements-refunds", activationWhen: "The campaign has or promises replacement, refund, return, dispute, or failed-delivery handling.", work: ["operate an explicit exception and financial-reconciliation path"], checks: ["test duplicate, reversal, and unresolved cases"], requiredExpectationIds: ["exception-proof"] },
      { id: "recurring-communications", activationWhen: "The approved fulfillment plan includes recurring backer updates or exception messages.", work: ["prepare factual cadence-bounded communications"], checks: ["verify claims, dates, approval, corrections, and response capture"], requiredExpectationIds: ["communications-proof"] },
    ],
    decisions: ["complete", "operating", "blocked", "repair-required", "no-go"],
    steps: ["Reconcile the funded-settled receipt into a minimized obligation ledger.", "Define terminal states per obligation type rather than imposing one shipment percentage.", "Execute only approved actions in immutable dated cycles and preserve exceptions.", "Use independent reconciliation before declaring any obligation or campaign complete."],
    completionBoundary: "Complete means every in-scope obligation has a directly evidenced terminal state; operating and blocked are honest durable outcomes, not failures to be hidden.",
  },
};
