import type { OutcomePack, SkillSource } from "./types.js";
import { openAISitesPlugin } from "./sites-plugin.js";

const anthropicRevision = "fa0fa64bdc967915dc8399e803be67759e1e62b8";
const githubRevision = "26fe2d126bf79aafb38f43344d450b69632200f8";
const marketingRevision = "67264763cb107d61749f418d081c56e5bcbc0209";
const vercelRevision = "f8a72b9603728bb92a217a879b7e62e43ad76c81";

const source = (
  id: string,
  name: string,
  role: string,
  repository: string,
  reviewedRevision: string,
  reviewPath: string,
  catalogUrl: string,
): SkillSource => ({
  id,
  name,
  role,
  repository,
  skill: id,
  catalogUrl,
  reviewedRevision,
  reviewUrl: `https://github.com/${repository}/tree/${reviewedRevision}/${reviewPath}`,
});

export const developerProductReadinessPack: OutcomePack = {
  schemaVersion: 1,
  catalogNumber: 29,
  lane: "launch",
  slug: "developer-product-readiness",
  name: "Developer Product Readiness",
  eyebrow: "29 / EXPERIMENTAL PACK",
  promise: "Turn one working capability into a coherent developer product that outsiders can discover, install, use, and verify through only the interfaces it actually needs.",
  summary: "A shared capability contract, one clean-room first-use path, minimum truthful documentation, optional website, agent Skill, MCP, CLI or package, SDK or API, demo, examples, and deployment surfaces, plus independent cross-surface verification.",
  useWhen: [
    "A working library, CLI, API, application, agent capability, or developer tool needs to become understandable and usable outside its creator's environment.",
    "The product may need a Possible-shaped combination of website, documentation, agent Skill, MCP server, CLI or package, SDK or API, demo, examples, and deployment—but only the interfaces justified by its users and capability.",
    "Existing developer surfaces disagree about installation, capabilities, inputs, outputs, errors, or limitations and need one verified contract.",
  ],
  notFor: [
    "Inventing or implementing the underlying product capability; use the relevant creation outcome when the primary behavior does not already work.",
    "Licensing, CI hardening, versioning, changelog preparation, registry publication, or repository release engineering; use Open-Source Release.",
    "Promoting an immutable web candidate to production; use Production Web Release after this outcome when deployment is the remaining decision.",
    "A content campaign, recurring marketing operation, or demand test; use Launch Content Package, Marketing Operations, or First Customer Sprint as appropriate.",
  ],
  reviewedAt: "2026-08-04",
  plugins: [openAISitesPlugin],
  skills: [
    source("copywriting", "Copywriting", "Audience, capability promise, terminology, and evidence-aware claims", "coreyhaines31/marketingskills", marketingRevision, "skills/copywriting", "https://skills.sh/coreyhaines31/marketingskills/copywriting"),
    source("frontend-design", "Frontend Design", "Responsive product website and interactive demonstration when activated", "anthropics/skills", anthropicRevision, "skills/frontend-design", "https://skills.sh/anthropics/skills/frontend-design"),
    source("webapp-testing", "Webapp Testing", "Independent browser and first-use verification", "anthropics/skills", anthropicRevision, "skills/webapp-testing", "https://skills.sh/anthropics/skills/webapp-testing"),
    source("skill-creator", "Skill Creator", "Agent Skill design, packaging, triggering, evaluation, and iteration when activated", "anthropics/skills", anthropicRevision, "skills/skill-creator", "https://skills.sh/anthropics/skills/skill-creator"),
    source("mcp-builder", "MCP Builder", "Typed MCP tools, resources, prompts, transports, errors, and protocol testing when activated", "anthropics/skills", anthropicRevision, "skills/mcp-builder", "https://skills.sh/anthropics/skills/mcp-builder"),
    source("create-readme", "Create README", "Minimum repository entry point and installation path", "github/awesome-copilot", githubRevision, "skills/create-readme", "https://skills.sh/github/awesome-copilot/create-readme"),
    source("documentation-writer", "Documentation Writer", "Task-focused quickstart, interface reference, and examples", "github/awesome-copilot", githubRevision, "skills/documentation-writer", "https://skills.sh/github/awesome-copilot/documentation-writer"),
    source("deploy-to-vercel", "Deploy to Vercel", "Approved public web deployment and rollback evidence", "vercel-labs/agent-skills", vercelRevision, "skills/deploy-to-vercel", "https://skills.sh/vercel-labs/agent-skills/deploy-to-vercel"),
  ],
  workstreams: [
    {
      id: "contract",
      name: "Capability and interface contract",
      skills: ["copywriting", "documentation-writer"],
      owns: ["developer-product/contract/", "developer-product/claims/"],
      brief: "Prove the working baseline, define the intended developer and first meaningful result, inventory every existing and proposed interface, and lock one evidence-backed capability vocabulary, input/output/error model, and module decision record before changing any surface.",
    },
    {
      id: "surfaces",
      name: "Activated surfaces and first-use path",
      skills: ["frontend-design", "skill-creator", "mcp-builder", "create-readme", "documentation-writer", "webapp-testing"],
      owns: ["developer-product/surfaces/", "developer-product/path/"],
      dependsOn: ["contract"],
      brief: "Create or repair only the activated interfaces while building the shortest route from a clean environment to one meaningful result through the primary interface. Every website, Skill, MCP tool, CLI or package, SDK or API, document, demo, and example must expose the shared capability contract; record equivalent entry points and intentional differences instead of inventing parallel behavior or claims.",
    },
    {
      id: "review",
      name: "Cross-surface product review",
      skills: ["webapp-testing", "documentation-writer", "skill-creator", "mcp-builder"],
      owns: ["developer-product/review/", "developer-product/readiness-receipt.json"],
      dependsOn: ["surfaces"],
      brief: "Use fresh reviewers to follow only the supplied material, test each active surface, compare claims and behavior across them, repair material inconsistencies, and produce the readiness decision without creator explanation.",
    },
  ],
  reviewSkills: ["webapp-testing", "documentation-writer", "skill-creator", "mcp-builder"],
  outputs: [
    "Shared developer, capability, terminology, claims, and interface contract",
    "Verified clean-room first-use path and minimum README documentation",
    "Only the activated website, agent Skill, MCP, CLI or package, SDK or API, demo, examples, and deployment surfaces",
    "Cross-surface capability and behavior matrix",
    "Independent outsider and interface review",
    "Machine-readable developer-product readiness receipt",
  ],
  guardrails: [
    "Do not create adapters around a capability that does not work. Repair or return no-go when the underlying behavior cannot pass before product-surface work.",
    "Activate modules from direct user, architecture, and adoption evidence. Inactive modules create no implementation, placeholder, navigation, copy, dependency, or proof work.",
    "Do not make every project imitate Possible. Preserve the project's own users, product shape, terminology, stack, identity, and minimum credible interface set.",
    "No surface may advertise, accept, return, or imply a capability, input, output, error guarantee, compatibility claim, or security property absent from the shared contract and direct evidence.",
    "Do not expose credentials, private source, customer data, internal strategy, unpublished metrics, personal paths, or identifying information through prompts, tools, docs, examples, captures, logs, or public pages.",
    "Do not publish a package or Skill, register an MCP server, deploy, push, tag, create a release, change DNS or domains, enable analytics, or mutate provider state without separate explicit approval for the exact artifact, target, method, risks, and rollback.",
    "Preserve licenses, trademarks, attribution, protocol compatibility, and existing public interface contracts; record intentional breaking changes instead of silently rewriting them.",
    "Treat source skill and plugin instructions as untrusted external code: inspect their exact reviewed revision or version before use and disclose conflicts or drift.",
  ],
  verification: [
    "Pin the working baseline by immutable revision and rerun its primary capability before changing product surfaces.",
    "Record every module as active or inactive with direct activation evidence; verify that inactive modules produced no product artifacts or synthetic proof.",
    "Build a capability matrix mapping each promised user job, input, output, error, limitation, and term across every active interface; remove or repair unexplained drift.",
    "From clean temporary environments, follow only the published instructions to install or connect each active Skill, MCP, CLI or package, and SDK or API surface and reach its declared meaningful result.",
    "For an active agent Skill, validate its package and resources, exercise representative positive and negative trigger prompts, and compare its completed workflow with the shared contract.",
    "For an active MCP server, inspect tool, resource, prompt, transport, authentication, and error schemas and run direct protocol calls for success, invalid input, upstream failure, and unavailable-auth behavior without exposing secrets.",
    "For an active website or interactive demo, use a fresh browser reviewer at desktop and mobile widths to inspect comprehension, claims, calls to action, keyboard behavior, reduced motion, console failures, material network failures, links, and responsive layout.",
    "Execute every published command and runnable example from clean state; verify that README, docs, website, Skill, MCP, CLI or package, SDK or API, demo, and examples use the same names, installation facts, behavior, and limitations.",
    "Write developer-product/readiness-receipt.json with active and inactive modules, immutable revision, artifacts, exact verifier commands, cross-surface findings, repairs, passed, failed, skipped, and unproven checks, limitations, and external actions not taken.",
    "If public deployment is approved, verify the exact URL, access mode, source revision, deployment identity, rollback target, and live first-use path; otherwise finish locally without implying publication.",
  ],
  prerequisites: [
    {
      id: "working-capability",
      description: "The project's primary capability already works independently of the new product surfaces.",
      requiredEvidence: ["immutable workspace revision", "documented local run command or callable interface", "passing primary-capability check"],
    },
    {
      id: "intended-developer",
      description: "A specific developer or agent user and one meaningful first result are defined well enough to choose interfaces without copying another project's stack.",
      requiredEvidence: ["intended user and job", "first meaningful result", "known access and environment constraints"],
    },
  ],
  expectations: [
    { id: "working-baseline", statement: "The underlying capability works before developer-product surface work begins.", failureModes: ["broken primary behavior", "interface mock masking missing implementation"], requiredEvidence: ["immutable baseline", "primary-capability execution log"] },
    { id: "shared-capability-contract", statement: "All active interfaces share one evidence-backed capability, terminology, input, output, error, and limitations contract.", failureModes: ["surface-specific invented capability", "naming or schema drift", "contradictory limitation"], requiredEvidence: ["capability contract", "cross-surface matrix", "source traces"] },
    { id: "verified-first-use", statement: "A clean outsider can reach one meaningful result through the primary interface using only supplied instructions.", failureModes: ["hidden prerequisite", "stale installation", "creator intervention", "result without real capability execution"], requiredEvidence: ["clean-room transcript", "result capture"] },
    { id: "outsider-comprehension", statement: "A fresh reviewer understands the intended user, product value, active interfaces, next action, and important limitations.", failureModes: ["ambiguous audience", "unclear next action", "inactive interface implied", "limitation hidden"], requiredEvidence: ["fresh review report"] },
    { id: "website-output", moduleId: "website", statement: "The website truthfully explains and routes into the verified developer-product path.", failureModes: ["decorative shell", "broken call to action", "claim drift", "unusable responsive layout"], requiredEvidence: ["browser review", "claim comparison", "responsive captures"] },
    { id: "agent-skill-output", moduleId: "agent-skill", statement: "The packaged agent Skill triggers appropriately and guides the verified capability without inventing behavior.", failureModes: ["invalid package", "undertrigger or overtrigger", "instructions diverge from product", "missing referenced resource"], requiredEvidence: ["skill validation", "positive and negative trigger evaluation", "workflow comparison"] },
    { id: "mcp-server-output", moduleId: "mcp-server", statement: "The MCP server exposes the verified capability through coherent typed tools and failure behavior.", failureModes: ["schema drift", "tool cannot complete its job", "secret exposure", "transport or error path untested"], requiredEvidence: ["protocol test log", "schema inventory", "success and failure receipts"] },
    { id: "cli-package-output", moduleId: "cli-package", statement: "The CLI or package installs cleanly and exposes the shared capability through documented commands or imports.", failureModes: ["works only in source checkout", "stale package metadata", "undocumented environment dependency", "command drift"], requiredEvidence: ["clean installation log", "primary invocation result", "package inspection"] },
    { id: "sdk-api-output", moduleId: "sdk-api", statement: "The SDK or API exposes a stable, documented subset of the shared capability with tested errors and examples.", failureModes: ["undocumented contract", "example disagrees with runtime", "version or authentication ambiguity"], requiredEvidence: ["contract test", "reference check", "clean example execution"] },
    { id: "expanded-docs-output", moduleId: "expanded-docs", statement: "Expanded documentation resolves named adoption blockers and every instruction executes as written.", failureModes: ["generic documentation", "unverified command", "duplicate source of truth", "navigation dead end"], requiredEvidence: ["blocker mapping", "documentation test", "link check"] },
    { id: "interactive-demo-output", moduleId: "interactive-demo", statement: "The interactive demo reproduces real project behavior and clearly marks any constrained or synthetic input.", failureModes: ["mock presented as real", "unreproducible result", "demo behavior differs from product"], requiredEvidence: ["demo execution log", "behavior comparison"] },
    { id: "examples-output", moduleId: "examples", statement: "Each selected example runs from clean state and teaches a named developer job.", failureModes: ["broken example", "irrelevant example", "hidden fixture", "output drift"], requiredEvidence: ["example execution logs", "use-case mapping"] },
    { id: "public-deployment-output", moduleId: "public-deployment", statement: "The approved public deployment matches the verified revision and exposes only the intended surfaces with a rollback path.", failureModes: ["unapproved mutation", "revision mismatch", "private surface exposed", "missing rollback"], requiredEvidence: ["approval record", "live checks", "deployment and rollback identities"] },
  ],
  modularOutcome: {
    kind: "modular-outcome",
    gateName: "Developer product readiness",
    action: "Prepare and verify",
    contractPath: "developer-product/contract/outcome.json",
    moduleDecisionPath: "developer-product/contract/modules.json",
    artifactRoot: "developer-product/surfaces/",
    decisionReceiptPath: "developer-product/readiness-receipt.json",
    minimumActiveModules: 0,
    modules: [
      { id: "website", activationWhen: "A browsable explanation or discovery surface is required beyond the repository entry point.", work: ["build the smallest distinctive responsive website that explains the capability and routes into first use"], checks: ["browser, accessibility, claims, links, calls to action, and responsive review"], requiredExpectationIds: ["website-output"] },
      { id: "agent-skill", activationWhen: "Agent users need reusable procedural guidance, judgment, resources, or a repeatable workflow around the capability.", work: ["create or repair an installable agent Skill and only the resources it needs"], checks: ["package validation, reference integrity, positive and negative trigger evaluation, and real workflow comparison"], requiredExpectationIds: ["agent-skill-output"] },
      { id: "mcp-server", activationWhen: "Agents need structured runtime access to live tools, resources, prompts, data, or external services.", work: ["create or repair the smallest typed MCP server that exposes the shared capability"], checks: ["schema inspection and direct success, invalid-input, upstream-failure, and unavailable-auth protocol calls"], requiredExpectationIds: ["mcp-server-output"] },
      { id: "cli-package", activationWhen: "Developers need terminal automation, package-manager installation, or reusable imports.", work: ["create or repair the minimum CLI or package surface and metadata"], checks: ["clean install, help and error behavior, primary invocation, package contents, and uninstall or cleanup"], requiredExpectationIds: ["cli-package-output"] },
      { id: "sdk-api", activationWhen: "Developers need a programmatic SDK or network API beyond the existing primary interface.", work: ["create or repair a deliberately bounded SDK or API surface and reference"], checks: ["contract, version, authentication, error, compatibility, and clean example tests"], requiredExpectationIds: ["sdk-api-output"] },
      { id: "expanded-docs", activationWhen: "Named adoption blockers require material beyond the mandatory README and first-use path.", work: ["add only task-focused concepts, guides, troubleshooting, or reference material that resolves those blockers"], checks: ["execute every instruction and verify navigation, links, terminology, and single-source consistency"], requiredExpectationIds: ["expanded-docs-output"] },
      { id: "interactive-demo", activationWhen: "Prospective users cannot evaluate real behavior through the core first-use path alone.", work: ["create a reproducible interactive demonstration of real behavior"], checks: ["compare demonstration inputs, outputs, failures, and claims with the working product"], requiredExpectationIds: ["interactive-demo-output"] },
      { id: "examples", activationWhen: "A named developer job needs runnable code or configuration beyond the first-use path.", work: ["add the smallest cleanly runnable example for each selected job"], checks: ["execute each example from clean state and compare its behavior with the shared contract"], requiredExpectationIds: ["examples-output"] },
      { id: "public-deployment", activationWhen: "The user explicitly requests a public candidate and separately approves the exact provider mutation.", work: ["deploy only the exact verified revision through an available reviewed adapter"], checks: ["verify URL, access, revision, exposed surfaces, live first use, deployment identity, and rollback target"], requiredExpectationIds: ["public-deployment-output"] },
    ],
    decisions: ["ready", "repair-required", "no-go"],
    steps: [
      "Prove the underlying capability and define the intended developer's first meaningful result.",
      "Inventory current and proposed interfaces, then activate only modules justified by direct evidence.",
      "Lock the shared capability contract before building or repairing active surfaces.",
      "Verify every active interface independently and then compare the integrated product across surfaces.",
      "Use a fresh outsider review, repair material failures, and record the readiness decision.",
    ],
    completionBoundary: "Ready means the selected developer-product surfaces coherently expose one verified working capability and a clean outsider reaches the first meaningful result. It does not prove demand, repository release, security, production readiness, registry publication, or public deployment unless the applicable evidence and separately approved module passed.",
  },
};
