// Generated by npm run packs:generate. Do not edit by hand.
import type { PackShowcase } from "./types.js";

const definePackShowcases = (showcases: Readonly<Record<string, PackShowcase>>) => showcases;

export const bundledPackShowcases = definePackShowcases({
  "cast-driven-product-story-animation": {
    "schemaVersion": 1,
    "description": "Gather turns four incomplete potluck contributions into one conflict-free plan in a finite, responsive browser animation.",
    "images": [
      {
        "src": "/pack-media/cast-driven-product-story-animation/media/gather-conflict-check.png",
        "alt": "Gather product animation checking four potluck contributions and exposing two conflicts",
        "caption": "The shared plan exposes serving and allergy conflicts",
        "cover": true
      },
      {
        "src": "/pack-media/cast-driven-product-story-animation/media/gather-complete-plan.png",
        "alt": "Gather product animation showing a complete potluck plan after both conflicts are repaired",
        "caption": "One complete, group-ready plan"
      },
      {
        "src": "/pack-media/cast-driven-product-story-animation/media/gather-cast-assembly.png",
        "alt": "Four abstract Gather contributors waiting to add dish, dietary, supply, and timing details",
        "caption": "Four distinct contributions enter one shared state"
      },
      {
        "src": "/pack-media/cast-driven-product-story-animation/media/gather-mobile.png",
        "alt": "Mobile layout of the Gather animation showing the contribution cards and conflict check",
        "caption": "Dedicated mobile composition"
      }
    ]
  },
  "developer-product-readiness": {
    "schemaVersion": 1,
    "description": "CSS Contrast Report turns a working contrast engine into a zero-dependency developer tool with one-command reports, stable CI exits, and JSON output.",
    "images": [
      {
        "src": "/pack-media/developer-product-readiness/media/css-report.png",
        "alt": "CSS source beside a terminal report listing color-pair contrast ratios and WCAG AA results",
        "caption": "One command produces the first useful report",
        "cover": true
      },
      {
        "src": "/pack-media/developer-product-readiness/media/css-report-ci.png",
        "alt": "Developer-tool board explaining stable exit codes and machine-readable JSON output",
        "caption": "Predictable local and CI behavior"
      },
      {
        "src": "/pack-media/developer-product-readiness/media/css-report-contract.png",
        "alt": "Diagram showing CLI and JavaScript interfaces sharing one deterministic contrast-report engine",
        "caption": "One capability contract across both interfaces"
      }
    ]
  },
  "first-customer-sprint": {
    "schemaVersion": 1,
    "description": "A bounded first-customer sprint for a private Outcome Pack workshop, with a precise offer and an honest stop before outreach.",
    "images": [
      {
        "src": "/pack-media/first-customer-sprint/media/private-pack-offer.png",
        "alt": "Draft SGD 750 private Outcome Pack workshop offer for small Singapore product teams",
        "caption": "A concrete offer with price, audience, and deliverable",
        "cover": true
      },
      {
        "src": "/pack-media/first-customer-sprint/media/private-pack-delivery.png",
        "alt": "Four-step workshop flow from reconstructing a real run to compiling a private Outcome Pack",
        "caption": "Bounded 90-minute delivery path"
      },
      {
        "src": "/pack-media/first-customer-sprint/media/private-pack-evidence.png",
        "alt": "Commercial evidence board showing the local offer exists while every customer and revenue measure remains zero",
        "caption": "The offer exists; demand remains unproven"
      },
      {
        "src": "/pack-media/first-customer-sprint/media/private-pack-gate.png",
        "alt": "Preflight checklist showing outreach blocked until owner approval and operating rules are supplied",
        "caption": "External action remains explicitly gated"
      }
    ]
  },
  "functional-hardware-prototype": {
    "schemaVersion": 1,
    "description": "A repair-required digital pre-build of a flat-pack corridor cat shelter with replaceable panels, ballast bays, and a captured roof.",
    "images": [
      {
        "src": "/pack-media/functional-hardware-prototype/media/cat-shelter-assembled.png",
        "alt": "Assembled CAD view of a flat-pack cat shelter with a triangular roof and arched entrance",
        "caption": "Digital assembly concept; physical validation pending",
        "cover": true
      },
      {
        "src": "/pack-media/functional-hardware-prototype/media/cat-shelter-exploded.png",
        "alt": "Exploded CAD view showing the cat shelter base, four walls, and two roof panels",
        "caption": "Replaceable flat-pack components"
      },
      {
        "src": "/pack-media/functional-hardware-prototype/media/cat-shelter-ballast-base.png",
        "alt": "CAD detail of the shelter base with four recessed ballast bays",
        "caption": "Concealed ballast-base concept"
      },
      {
        "src": "/pack-media/functional-hardware-prototype/media/cat-shelter-roof-lock.png",
        "alt": "Underside CAD detail of one roof panel and its capture rails",
        "caption": "Roof-lock geometry pending physical fit testing"
      }
    ],
    "cad": {
      "caption": "Download the STEP assembly for inspection; this digital prototype has not been fabricated or physically validated.",
      "downloads": [
        {
          "src": "/pack-media/functional-hardware-prototype/media/cat-shelter.step",
          "format": "step",
          "label": "Download STEP assembly"
        }
      ]
    }
  },
  "html-css-animated-product-launch-film": {
    "schemaVersion": 1,
    "description": "A complete launch film made as standalone HTML and CSS, then rendered with its original Codex-produced soundtrack.",
    "video": {
      "src": "/pack-media/html-css-animated-product-launch-film/media/possible-launch-film.mp4",
      "poster": "/pack-media/html-css-animated-product-launch-film/media/possible-launch-film-poster.jpg",
      "caption": "Possible launch film — from a world of unknown Codex capabilities to one outcome you can run."
    }
  },
  "mechanical-cad-review": {
    "schemaVersion": 1,
    "description": "A mechanical review that catches an 8.9 mm usable passage in a nominal 12.8 mm cable clip and turns the failure into a repair plan.",
    "images": [
      {
        "src": "/pack-media/mechanical-cad-review/media/cable-clip-review.png",
        "alt": "Mechanical CAD review board marking the cable clip repair-required due to fit, snap, and load-path issues",
        "caption": "Repair-required review overview",
        "cover": true
      },
      {
        "src": "/pack-media/mechanical-cad-review/media/cable-clip-fit-section.png",
        "alt": "Plan-section comparison showing an 8.9 millimeter passage cannot accept the stated 12 millimeter cable",
        "caption": "The decisive fit failure"
      },
      {
        "src": "/pack-media/mechanical-cad-review/media/cable-clip-load-path.png",
        "alt": "Named cable-clip load path from cable through ring, neck, base, adhesive, and desk",
        "caption": "A valid solid is not yet a valid load path"
      },
      {
        "src": "/pack-media/mechanical-cad-review/media/cable-clip-repair-plan.png",
        "alt": "Four-part repair plan covering cable axis, passage, flex geometry, adhesive, and physical coupons",
        "caption": "Repair the geometry, then test the interfaces"
      }
    ],
    "cad": {
      "caption": "Inspect the exact STEP source reviewed in this example.",
      "downloads": [
        {
          "src": "/pack-media/mechanical-cad-review/media/cable-clip-v0.step",
          "format": "step",
          "label": "Download reviewed STEP file"
        }
      ]
    }
  },
  "original-strudel-soundtrack": {
    "schemaVersion": 1,
    "description": "Lantern Rain is an original 80-second Strudel miniature with warm mallets, sparse percussion, a gentle lift, and a quiet resolution.",
    "video": {
      "src": "/pack-media/original-strudel-soundtrack/media/lantern-rain-preview.mp4",
      "poster": "/pack-media/original-strudel-soundtrack/media/lantern-rain-cover.png",
      "caption": "A 30-second audio-backed preview of the lift and resolution; final human listening acceptance is pending."
    }
  },
  "playable-web-game": {
    "schemaVersion": 1,
    "description": "Orbit Courier is a polished Three.js gravity-routing game where one thrust control bends a predicted trajectory through three delivery routes.",
    "images": [
      {
        "src": "/pack-media/playable-web-game/media/orbit-courier-active.png",
        "alt": "Orbit Courier gameplay with a spacecraft, gravity wells, targets, and a live predicted route",
        "caption": "Live gravity-routing gameplay",
        "cover": true
      },
      {
        "src": "/pack-media/playable-web-game/media/orbit-courier-opening.png",
        "alt": "Orbit Courier opening screen introducing the single-thrust control and first route",
        "caption": "Immediate, legible first-play state"
      },
      {
        "src": "/pack-media/playable-web-game/media/orbit-courier-complete.png",
        "alt": "Orbit Courier route-complete screen with delivery result and next-route action",
        "caption": "Complete route and progression state"
      }
    ]
  },
  "polished-editable-powerpoint-presentation": {
    "schemaVersion": 1,
    "description": "A restrained, fully editable investment-committee deck for an illustrative three-building community solar feasibility decision.",
    "images": [
      {
        "src": "/pack-media/polished-editable-powerpoint-presentation/media/solar-economics.png",
        "alt": "Editable presentation slide showing illustrative community solar capital, savings, generation, and simple payback",
        "caption": "Illustrative economics with explicit limitations",
        "cover": true
      },
      {
        "src": "/pack-media/polished-editable-powerpoint-presentation/media/solar-pilot-structure.png",
        "alt": "Editable presentation slide diagramming three buildings within one community solar pilot",
        "caption": "One programme, three separately assessable sites"
      },
      {
        "src": "/pack-media/polished-editable-powerpoint-presentation/media/solar-decision.png",
        "alt": "Community Solar Pilot title slide framing the decision to proceed to detailed feasibility",
        "caption": "Decision-led opening"
      },
      {
        "src": "/pack-media/polished-editable-powerpoint-presentation/media/solar-recommendation.png",
        "alt": "Recommendation slide authorizing analysis only and listing three feasibility workstreams",
        "caption": "A bounded next-gate recommendation"
      }
    ]
  },
  "production-logo-system": {
    "schemaVersion": 1,
    "description": "A calm geometric identity for fictional Aster Rail, engineered as an editable light/dark, optical-size, avatar, and favicon system.",
    "images": [
      {
        "src": "/pack-media/production-logo-system/media/aster-rail-system.png",
        "alt": "Aster Rail logo system board with primary mark, dark lockup, colors, compact lockups, and invariants",
        "caption": "Selected identity and core system",
        "cover": true
      },
      {
        "src": "/pack-media/production-logo-system/media/aster-rail-interface.png",
        "alt": "Aster Rail identity applied to desktop and mobile regional-planning interfaces",
        "caption": "Real-size product application"
      },
      {
        "src": "/pack-media/production-logo-system/media/aster-rail-optical.png",
        "alt": "Display and small optical versions of the Aster Rail mark with delivered icon sizes",
        "caption": "Optical-size family from 16 pixels upward"
      },
      {
        "src": "/pack-media/production-logo-system/media/aster-rail-surfaces.png",
        "alt": "Aster Rail logo and product examples tuned for light and dark surfaces",
        "caption": "Surface-specific contrast tuning"
      }
    ]
  },
  "production-readiness-decision": {
    "schemaVersion": 1,
    "description": "An evidence-led production review that turns incomplete fictional prototype data into a bounded repair-required decision.",
    "images": [
      {
        "src": "/pack-media/production-readiness-decision/media/docklight-decision.png",
        "alt": "DockLight production-readiness dashboard concluding repair required before a fictional 500-unit pilot",
        "caption": "A decision tied to one named commitment",
        "cover": true
      },
      {
        "src": "/pack-media/production-readiness-decision/media/docklight-gates.png",
        "alt": "Six accountable release gates covering configuration, defects, claims, process, economics, and support",
        "caption": "Close the proof gaps before order release"
      },
      {
        "src": "/pack-media/production-readiness-decision/media/docklight-evidence.png",
        "alt": "Evidence coverage table separating framed, partial, missing, and failed readiness evidence",
        "caption": "Plans are not proof"
      },
      {
        "src": "/pack-media/production-readiness-decision/media/docklight-scope.png",
        "alt": "Frozen DockLight scope and decision rules for ready, repair-required, and no-go states",
        "caption": "One revision, one commitment"
      }
    ]
  },
  "robot-digital-prototype": {
    "schemaVersion": 1,
    "description": "A ten-link robot-snake digital prototype with an inspectable browser model and engineering source file.",
    "images": [
      {
        "src": "/pack-media/robot-digital-prototype/media/robot-snake-iso.png",
        "alt": "Isometric view of a ten-link robot snake CAD assembly",
        "caption": "Complete articulated assembly",
        "cover": true
      },
      {
        "src": "/pack-media/robot-digital-prototype/media/robot-snake-iso-opposite.png",
        "alt": "Opposite isometric view of the robot snake CAD assembly",
        "caption": "Opposite assembly view"
      },
      {
        "src": "/pack-media/robot-digital-prototype/media/robot-snake-top.png",
        "alt": "Top view of the robot snake CAD assembly",
        "caption": "Top view and link spacing"
      }
    ],
    "cad": {
      "preview": "/pack-media/robot-digital-prototype/media/robot-snake.glb",
      "poster": "/pack-media/robot-digital-prototype/media/robot-snake-iso.png",
      "caption": "Rotate and inspect the complete linked assembly in the browser.",
      "downloads": [
        {
          "src": "/pack-media/robot-digital-prototype/media/robot-snake.step",
          "format": "step",
          "label": "Download STEP assembly"
        }
      ]
    }
  },
  "web-presentation": {
    "schemaVersion": 1,
    "description": "A tactile eight-scene browser presentation tracing one packet through routing, congestion, retries, arrival, and reassembly.",
    "images": [
      {
        "src": "/pack-media/web-presentation/media/packet-routing.png",
        "alt": "Browser presentation scene showing routers making one local forwarding decision at a time",
        "caption": "Each router chooses the next hop",
        "cover": true
      },
      {
        "src": "/pack-media/web-presentation/media/packet-congestion.png",
        "alt": "Browser presentation scene explaining queueing delay at a busy outbound link",
        "caption": "Delay grows where packets wait"
      },
      {
        "src": "/pack-media/web-presentation/media/packet-reassembly.png",
        "alt": "Browser presentation scene showing out-of-order packets restored to their original sequence",
        "caption": "The destination restores sequence"
      },
      {
        "src": "/pack-media/web-presentation/media/packet-deck.png",
        "alt": "Contact sheet of the complete eight-scene packet journey browser presentation",
        "caption": "Complete narrative arc"
      }
    ]
  },
  "website-reference-reconstruction": {
    "schemaVersion": 1,
    "description": "An identity-safe reconstruction of a licensed open-source portfolio across desktop, dark mode, and a responsive mobile drawer.",
    "images": [
      {
        "src": "/pack-media/website-reference-reconstruction/media/night-orbit-light.png",
        "alt": "Side-by-side light-mode comparison of a licensed portfolio reference and the Night Orbit reconstruction",
        "caption": "Desktop light-mode comparison",
        "cover": true
      },
      {
        "src": "/pack-media/website-reference-reconstruction/media/night-orbit-mobile.png",
        "alt": "Side-by-side mobile drawer comparison of the licensed reference and reconstructed portfolio",
        "caption": "Responsive navigation comparison"
      },
      {
        "src": "/pack-media/website-reference-reconstruction/media/night-orbit-dark.png",
        "alt": "Side-by-side dark-mode comparison of the licensed portfolio reference and reconstruction",
        "caption": "Desktop dark-mode comparison"
      }
    ]
  },
  "working-web-app": {
    "schemaVersion": 1,
    "description": "Marketboard is a local-first weekend-market organizer with constraint-aware filtering, vendor editing, stage movement, and persistent state.",
    "images": [
      {
        "src": "/pack-media/working-web-app/media/marketboard-overview.png",
        "alt": "Marketboard web app showing weekend market metrics, search filters, and vendor planning columns",
        "caption": "Complete local planning workspace",
        "cover": true
      },
      {
        "src": "/pack-media/working-web-app/media/marketboard-filter.png",
        "alt": "Marketboard filtered to vendors whose setup requires mains power",
        "caption": "Constraint-aware planning filter"
      },
      {
        "src": "/pack-media/working-web-app/media/marketboard-edit.png",
        "alt": "Marketboard vendor-editing dialog with status, stall, arrival, category, and operational needs",
        "caption": "Clear vendor editing flow"
      }
    ]
  }
});
