// Generated by npm run packs:generate. Do not edit by hand.
import type { CompanyRecord, ProductRecord } from "./types.js";

export const rawCompanies: CompanyRecord[] = [
  {
    "schemaVersion": 1,
    "id": "heygen",
    "name": "HeyGen",
    "website": "https://www.heygen.com"
  }
];
export const rawProducts: ProductRecord[] = [
  {
    "schemaVersion": 1,
    "id": "heygen/hyperframes",
    "name": "HyperFrames",
    "company": "heygen",
    "summary": "Create motion graphics, explainers, and launch films from the same HTML and CSS agents already know.",
    "logoUrl": "https://raw.githubusercontent.com/heygen-com/hyperframes/3e4b08cdc18642d468d53f34c2fb64ab437807ae/docs/logo/symbol-light.svg",
    "website": "https://github.com/heygen-com/hyperframes",
    "docsUrl": "https://hyperframes.heygen.com",
    "commerce": {
      "availability": "free",
      "agentCheckout": "not-required",
      "methods": [],
      "pricingUrl": null
    }
  }
];
