// Generated by npm run packs:generate. Do not edit by hand.
import type { CompanyRecord, ProductRecord } from "./types.js";

export const rawCompanies: CompanyRecord[] = [
  {
    "schemaVersion": 1,
    "id": "heygen",
    "name": "HeyGen",
    "website": "https://www.heygen.com"
  }
];
export const rawProducts: ProductRecord[] = [
  {
    "schemaVersion": 1,
    "id": "heygen/hyperframes",
    "name": "HyperFrames",
    "company": "heygen",
    "summary": "An open-source framework for agents to create and render video from HTML.",
    "website": "https://github.com/heygen-com/hyperframes",
    "docsUrl": "https://hyperframes.heygen.com",
    "commerce": {
      "availability": "free",
      "agentCheckout": "not-required",
      "methods": [],
      "pricingUrl": null
    }
  }
];
