// A schema-shaped visual/test fixture. Product builds always resolve the real
// @possible/knowledge/data workspace export and never bundle this module.
export const knowledgeGraphData = {
  nodes: [
    {
      id: "fixture",
      type: "topic",
      title: "Operational knowledge",
      summary: "A top-level field of contributor-maintained working knowledge.",
      tags: ["field"],
      recommendations: [{
        statement: "Begin with the outcome, then narrow by the constraints that change the productive route.",
        applicability: ["The outcome belongs to this field"],
        counterconditions: ["Another field owns the primary artifact"],
        alternatives: [],
        sources: [{ title: "Maintained source", url: "https://example.com", publisher: "Example" }],
        contributors: [{ id: "maintainer", name: "Fixture maintainer" }],
        reviewedAt: "2026-07-17",
        confidence: "high",
      }],
    },
    {
      id: "fixture/outcome",
      type: "topic",
      title: "Outcome family",
      summary: "A concrete family of outcomes with shared technical constraints.",
      recommendations: [{
        statement: "Classify the outcome before selecting tools or providers.",
        applicability: ["Multiple implementation routes are available"],
        counterconditions: ["The route is already fixed by an external requirement"],
        alternatives: [{ nodeId: "fixture/outcome-alt", reason: "A different constraint dominates." }],
        sources: [], contributors: [], reviewedAt: "2026-07-17", confidence: "medium",
      }],
    },
    {
      id: "fixture/practice",
      type: "practice",
      title: "Conditional practice",
      summary: "A productive default when its stated constraints fit.",
      recommendations: [{
        statement: "Use the practice when fast iteration and maintainable outputs matter together.",
        applicability: ["Fast iteration matters", "The output must remain maintainable"],
        counterconditions: ["A specialist workflow is required"],
        alternatives: [{ nodeId: "fixture/practice-alt", reason: "Prefer the specialist route." }],
        sources: [], contributors: [], reviewedAt: "2026-07-17", confidence: "high",
      }],
      practice: { outputs: ["Maintainable artifact", "Decision record"], checks: ["Acceptance criteria pass", "Artifact can be reproduced"] },
    },
    {
      id: "fixture/tool",
      type: "tool",
      title: "Productive tool",
      summary: "A maintained tool with a clear role in the route.",
      recommendations: [{ statement: "Select only when its runtime fits.", applicability: ["Its runtime is supported"], counterconditions: ["An incompatible runtime is required"], alternatives: [], sources: [], contributors: [], reviewedAt: "2026-07-17", confidence: "medium" }],
    },
    {
      id: "fixture/provider",
      type: "provider",
      title: "Provider capability",
      summary: "An external service with documented inputs, outputs, and approval boundaries.",
      recommendations: [{
        statement: "Shortlist this provider only after its supported capability and live constraints are checked.",
        applicability: ["The supported input matches", "The provider serves the required route"],
        counterconditions: ["A required capability is unsupported"],
        alternatives: [],
        sources: [{ title: "Provider capability reference", url: "https://example.com/provider", publisher: "Example provider" }],
        contributors: [{ id: "maintainer", name: "Fixture maintainer" }],
        reviewedAt: "2026-07-17",
        confidence: "medium",
      }],
      provider: {
        officialUrl: "https://example.com/provider",
        capabilities: [
          { key: "input", label: "Supported input", status: "supported" },
          { key: "output", label: "Verified output", status: "supported" },
        ],
        knownConstraints: [{ statement: "An account and supported region are required." }],
        handoffs: [{ channel: "website", purpose: "Open the provider handoff and prepare the supported artifact.", approvalRequired: true, externalEffect: true, source: { url: "https://example.com/provider/start" } }],
        unknowns: [{ field: "pricing", statement: "Current price must be checked live." }],
      },
    },
    {
      id: "fixture/action",
      type: "action",
      title: "Approval-gated handoff",
      summary: "A documented action that leaves privileged execution in the agent host.",
      recommendations: [{ statement: "Prepare the handoff, then request captain approval before the external effect.", applicability: ["The provider route is selected"], counterconditions: ["Required authorization is unavailable"], alternatives: [], sources: [], contributors: [], reviewedAt: "2026-07-17", confidence: "high" }],
      action: { access: "external-approval", requiresApproval: true, providerId: "fixture/provider", steps: ["Validate the artifact", "Show the proposed external effect", "Request captain approval", "Perform the handoff"], produces: ["External handoff receipt"] },
    },
    { id: "fixture/practice-alt", type: "practice", title: "Specialist route", summary: "A deliberate alternative for specialist constraints.", recommendations: [] },
    { id: "fixture/outcome-alt", type: "topic", title: "Alternative outcome", summary: "A neighboring outcome with a different primary constraint.", recommendations: [] },
    { id: "fixture/check", type: "practice", title: "Verification practice", summary: "Proof that the claimed result actually holds.", recommendations: [] },
  ],
  edges: [
    { source: "fixture/outcome", target: "fixture", type: "hierarchy" },
    { source: "fixture/practice", target: "fixture/outcome", type: "relevance" },
    { source: "fixture/tool", target: "fixture/practice", type: "compatibility" },
    { source: "fixture/provider", target: "fixture/practice", type: "support" },
    { source: "fixture/action", target: "fixture/provider", type: "invocation" },
    { source: "fixture/practice", target: "fixture/practice-alt", type: "alternatives" },
    { source: "fixture/outcome", target: "fixture/outcome-alt", type: "alternatives" },
    { source: "fixture/check", target: "fixture/practice", type: "relevance" },
  ],
};
export default knowledgeGraphData;
