import type { WikiCorpus } from "@possible/knowledge";

export const testWikiCorpus: WikiCorpus = {
  pages: [
    {
      slug: "web",
      title: "Web",
      summary: "Operational knowledge for browser-delivered work.",
      body: [
        "## What this makes possible",
        "",
        "Web knowledge supports browser surfaces and routes into narrower pages.",
        "",
        "## A common approach",
        "",
        "Start with the primary surface and continue with [Browser applications](/wiki/browser-applications).",
      ].join("\n"),
      tags: ["browser", "frontend"],
      reviewedAt: "2026-07-17",
      sources: [{ title: "React", url: "https://react.dev/" }],
      links: ["browser-applications"],
    },
    {
      slug: "browser-applications",
      title: "Browser applications",
      summary: "Interactive browser software with routes, state, and data flow.",
      body: [
        "## What this makes possible",
        "",
        "Applications can support multiple views and accessible user flows.",
        "",
        "## A common approach",
        "",
        "Choose a stack only after the constraints are visible. Compare [Vite with React](/wiki/vite-react).",
      ].join("\n"),
      tags: ["application", "routing"],
      reviewedAt: "2026-07-17",
      sources: [{ title: "Sunsetting Create React App", url: "https://react.dev/blog/2025/02/14/sunsetting-create-react-app" }],
      links: ["vite-react"],
    },
    {
      slug: "vite-react",
      title: "Vite with React",
      summary: "A lightweight setup for client-rendered applications.",
      body: [
        "[Vite](https://vite.dev/) supplies a fast development server.",
        "",
        "## Use this when",
        "",
        "Use this setup when the app is intentionally client-rendered and continue with [Browser applications](/wiki/browser-applications).",
        "",
        "Raw HTML stays literal: <span data-testid=\"unsafe-html\">unsafe html</span>.",
      ].join("\n"),
      tags: ["react", "vite"],
      reviewedAt: "2026-07-17",
      sources: [{ title: "Vite guide", url: "https://vite.dev/guide/" }],
      links: ["browser-applications"],
    },
  ],
};
