import type { WikiCorpus } from "@possible/knowledge";

export const testWikiCorpus: WikiCorpus = {
  pages: [
    {
      slug: "web",
      title: "Web",
      summary: "Operational knowledge for browser-delivered work.",
      body: [
        "## What this guide covers",
        "",
        "Web knowledge helps readers understand browser surfaces and related subjects.",
        "",
        "## A common approach",
        "",
        "Start with the primary surface and continue with [Browser applications](/wiki/browser-applications).",
      ].join("\n"),
      tags: ["browser", "frontend"],
      reviewedAt: "2026-07-17",
      sources: [{ title: "React", url: "https://react.dev/" }],
      links: ["browser-applications", "custom-manufactured-parts"],
    },
    {
      slug: "browser-applications",
      title: "Browser applications",
      summary: "Interactive browser software with navigation, state, and data flow.",
      body: [
        "## What this guide covers",
        "",
        "Applications can support multiple views and accessible user flows.",
        "",
        "## A common approach",
        "",
        "Compare implementation approaches only after the constraints are visible. Read [Vite with React](/wiki/vite-react) for related context.",
      ].join("\n"),
      tags: ["application", "routing"],
      reviewedAt: "2026-07-17",
      sources: [{ title: "Sunsetting Create React App", url: "https://react.dev/blog/2025/02/14/sunsetting-create-react-app" }],
      links: ["vite-react"],
    },
    {
      slug: "vite-react",
      title: "Vite with React",
      summary: "A lightweight setup for client-rendered applications.",
      body: [
        "[Vite](https://vite.dev/) supplies a fast development server.",
        "",
        "## Use this when",
        "",
        "This setup can fit intentionally client-rendered apps. [Browser applications](/wiki/browser-applications) provides related context.",
        "",
        "Raw HTML stays literal: <span data-testid=\"unsafe-html\">unsafe html</span>.",
      ].join("\n"),
      tags: ["react", "vite"],
      reviewedAt: "2026-07-17",
      sources: [{ title: "Vite guide", url: "https://vite.dev/guide/" }],
      links: ["browser-applications"],
    },
    {
      slug: "manufacturing",
      title: "Manufacturing",
      summary: "Operational knowledge for turning controlled designs into fabricated parts.",
      body: [
        "## What this guide covers",
        "",
        "Manufacturing knowledge covers outcomes that end in physical parts.",
        "",
        "Read [Custom manufactured parts](/wiki/custom-manufactured-parts) for related fabrication context, or [Web](/wiki/web) for wholly digital work.",
      ].join("\n"),
      tags: ["fabrication", "cad"],
      reviewedAt: "2026-07-17",
      sources: [{ title: "NIST STEP reference", url: "https://example.com/step" }],
      links: ["custom-manufactured-parts", "web"],
    },
    {
      slug: "custom-manufactured-parts",
      title: "Custom manufactured parts",
      summary: "Field guidance about moving design intent toward fabrication and inspection.",
      body: "This guide explains manufacturing requirements and why approval evidence matters.",
      tags: ["manufacturing", "fabrication"],
      aliases: ["custom manufactured part"],
      reviewedAt: "2026-07-17",
      sources: [{ title: "Manufacturing reference", url: "https://example.com/manufacturing" }],
      links: ["manufacturing"],
    },
  ],
};
