import { readFile, readdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const directory = join(root, "skills", "possible");
const [skill, metadata, catalog, entries] = await Promise.all([
  readFile(join(directory, "SKILL.md"), "utf8"),
  readFile(join(directory, "agents", "openai.yaml"), "utf8"),
  readFile(join(directory, "references", "packs.md"), "utf8"),
  readdir(directory),
]);
const errors = [];
const check = (condition, message) => { if (!condition) errors.push(message); };
const validateSkillStructure = async (name, allowedEntries) => {
  const skillDirectory = join(root, "skills", name);
  const [contents, skillEntries] = await Promise.all([
    readFile(join(skillDirectory, "SKILL.md"), "utf8"),
    readdir(skillDirectory),
  ]);
  const skillFrontmatter = contents.match(/^---\n([\s\S]*?)\n---\n/);
  check(Boolean(skillFrontmatter), `${name}/SKILL.md must start with frontmatter`);
  if (skillFrontmatter) {
    const keys = [...skillFrontmatter[1].matchAll(/^([a-z]+):/gm)].map((match) => match[1]).sort();
    check(JSON.stringify(keys) === JSON.stringify(["description", "name"]), `${name} frontmatter must contain only name and description`);
    check(new RegExp(`^name: ${name}$`, "m").test(skillFrontmatter[1]), `${name} frontmatter must use the directory name`);
  }
  check(skillEntries.every((entry) => allowedEntries.includes(entry)), `${name} contains an unexpected top-level file`);
};

await validateSkillStructure("possible", ["SKILL.md", "agents", "references"]);
const frontmatter = skill.match(/^---\n([\s\S]*?)\n---\n/);
check(Boolean(frontmatter), "SKILL.md must start with frontmatter");
if (frontmatter) {
  const keys = [...frontmatter[1].matchAll(/^([a-z]+):/gm)].map((match) => match[1]).sort();
  check(JSON.stringify(keys) === JSON.stringify(["description", "name"]), "frontmatter must contain only name and description");
}
for (const phrase of [
  "What would you like to make possible today?",
  "one structured prompt",
  "optionally, the repository and directory for each specialized agent Skill it needs",
  "checklist of expectations",
  "search_packs",
  "possible bookmark add",
  "possible bookmark list",
  "possible bookmark remove",
  "promise",
  "prompt",
  "notFor",
  "expectations",
  "listed",
  "experimental",
  "verified",
  "If no pack fits",
  "Let the user choose",
  "Want me to proceed with this Outcome Pack?",
  "Save the exact pack used for the run at `.possible/pack.json`",
  "Apply the pack's prompt",
  "cheapest reliable method available",
  "Do not create extra verification artifacts",
  "Do not create workstreams",
  "possible pack init",
  "possible pack validate",
  "possible pack compile",
  "possible pack inspect",
  "possible pack export",
  "owner/repository/slug",
  "exact commit",
  "Authors cannot assign Possible trust",
  "A pack is direction, not permission",
]) {
  check(skill.toLowerCase().includes(phrase.toLowerCase()), `SKILL.md must include '${phrase}'`);
}
check(!/^Recommend (?:the )?[A-Z][^\n]+(?:Pack|Outcome)/m.test(skill), "SKILL.md must not hard-code recommendations for named packs");
check(!/\blong prompt\b|\buseWhen\b|\bRun Prompt\b/i.test(skill), "SKILL.md must describe the current minimal pack contract");
for (const gate of ["credentials", "deployment", "publishing", "spending", "fabrication", "account access", "production changes"]) {
  check(skill.toLowerCase().includes(gate.toLowerCase()), `SKILL.md must retain the ${gate} gate`);
}
check(catalog.includes("<!-- Generated by scripts/sync-pack-reference.mjs. Do not edit by hand. -->"), "pack reference must be a generated catalog snapshot");
check(/## .+\n\n- Identity: `[^`]+\/[^`]+\/[^`]+`/.test(catalog), "pack reference must include namespaced catalog identities");
check(/- Status: `(listed|experimental|verified)`/.test(catalog), "pack reference must expose catalog trust status");
check(/- Promise: /.test(catalog) && /- Not for:/.test(catalog) && /- Expectations:/.test(catalog) && /- Skills:/.test(catalog), "pack reference must publish generic selection data");
check(/short_description: "Find and run Outcome Packs"/.test(metadata), "metadata must state the discovery promise");
check(metadata.includes("$possible"), "default prompt must mention $possible");
check(entries.every((entry) => ["SKILL.md", "agents", "references"].includes(entry)), "skill directory contains unexpected top-level files");
check(skill.split("\n").length <= 500, "SKILL.md must stay under 500 lines");
if (errors.length) throw new Error(`Possible skill validation failed:\n- ${errors.join("\n- ")}`);
console.log("The Possible skill is valid.");
