Output cli-search.mp4
Output cli-search.gif
Set Shell "bash"
Set FontSize 20
Set Width 1280
Set Height 800
Set Padding 28
Set Theme "Catppuccin Mocha"
Set TypingSpeed 40ms
Hide
Type "export POSSIBLE_TELEMETRY=0 PS1='$ ' && clear"
Enter
Show
Sleep 700ms
Type `possible search "teach a robot duck a dance" | head -5`
Sleep 300ms
Enter
Sleep 3000ms
Type "possible fetch kh79hk92ss2q5d96kb9f6h0aan8dnzdt | fold -s -w 86 | head -15"
Sleep 300ms
Enter
Sleep 7000ms
